version: '3.8'

services:
  db:
    image: postgres:16.2
    # restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ms_figueroa_jimenez
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "4444:80"
  # service of redis
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"

volumes:
  pg-data: